name: Yocto Build

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build Yocto
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          sudo apt-get update
                  sudo apt-get install -y gawk wget git-core diffstat unzip texinfo gcc-multilib build-essential chrpath socat cpio  xz-utils debianutils iputils-ping libsdl1.2-dev xterm

      - name: Clone Yocto Poky repository
        run: git clone git://git.yoctoproject.org/poky.git

      - name: Clone Raspberry Pi layer
        run: git clone git://git.yoctoproject.org/meta-raspberrypi.git poky/meta-raspberrypi

      - name: Build Yocto
        run: |
          cd poky
          source oe-init-build-env
          bitbake core-image-minimal

      # Add additional steps if needed, such as deploying the build artifacts
